/* This file was generated by SableCC (http://www.sablecc.org/). */

package fet.compiler.analysis;

import fet.compiler.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAAxiomS(AAxiomS node);
    void caseAIdS(AIdS node);
    void caseALL(ALL node);
    void caseASL(ASL node);

    void caseTIdent(TIdent node);
    void caseTLpar(TLpar node);
    void caseTRpar(TRpar node);
    void caseTComma(TComma node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
