/* This file was generated by SableCC (http://www.sablecc.org/). */

package fet.calc.node;

import fet.calc.analysis.*;

@SuppressWarnings("nls")
public final class APlusExpre extends PExpre
{
    private PExpre _expre_;
    private TPlus _plus_;
    private PTerm _term_;

    public APlusExpre()
    {
        // Constructor
    }

    public APlusExpre(
        @SuppressWarnings("hiding") PExpre _expre_,
        @SuppressWarnings("hiding") TPlus _plus_,
        @SuppressWarnings("hiding") PTerm _term_)
    {
        // Constructor
        setExpre(_expre_);

        setPlus(_plus_);

        setTerm(_term_);

    }

    @Override
    public Object clone()
    {
        return new APlusExpre(
            cloneNode(this._expre_),
            cloneNode(this._plus_),
            cloneNode(this._term_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlusExpre(this);
    }

    public PExpre getExpre()
    {
        return this._expre_;
    }

    public void setExpre(PExpre node)
    {
        if(this._expre_ != null)
        {
            this._expre_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expre_ = node;
    }

    public TPlus getPlus()
    {
        return this._plus_;
    }

    public void setPlus(TPlus node)
    {
        if(this._plus_ != null)
        {
            this._plus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plus_ = node;
    }

    public PTerm getTerm()
    {
        return this._term_;
    }

    public void setTerm(PTerm node)
    {
        if(this._term_ != null)
        {
            this._term_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._term_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expre_)
            + toString(this._plus_)
            + toString(this._term_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expre_ == child)
        {
            this._expre_ = null;
            return;
        }

        if(this._plus_ == child)
        {
            this._plus_ = null;
            return;
        }

        if(this._term_ == child)
        {
            this._term_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expre_ == oldChild)
        {
            setExpre((PExpre) newChild);
            return;
        }

        if(this._plus_ == oldChild)
        {
            setPlus((TPlus) newChild);
            return;
        }

        if(this._term_ == oldChild)
        {
            setTerm((PTerm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
