/* This file was generated by SableCC (http://www.sablecc.org/). */

package fet.compiler.parser;

import fet.compiler.node.*;
import fet.compiler.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTIdent(@SuppressWarnings("unused") TIdent node)
    {
        this.index = 0;
    }

    @Override
    public void caseTLpar(@SuppressWarnings("unused") TLpar node)
    {
        this.index = 1;
    }

    @Override
    public void caseTRpar(@SuppressWarnings("unused") TRpar node)
    {
        this.index = 2;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 3;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 4;
    }
}
