/* This file was generated by SableCC (http://www.sablecc.org/). */

package fet.compiler.node;

import fet.compiler.analysis.*;

@SuppressWarnings("nls")
public final class ALL extends PL
{
    private PL _l_;
    private TComma _comma_;
    private PS _s_;

    public ALL()
    {
        // Constructor
    }

    public ALL(
        @SuppressWarnings("hiding") PL _l_,
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PS _s_)
    {
        // Constructor
        setL(_l_);

        setComma(_comma_);

        setS(_s_);

    }

    @Override
    public Object clone()
    {
        return new ALL(
            cloneNode(this._l_),
            cloneNode(this._comma_),
            cloneNode(this._s_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALL(this);
    }

    public PL getL()
    {
        return this._l_;
    }

    public void setL(PL node)
    {
        if(this._l_ != null)
        {
            this._l_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._l_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PS getS()
    {
        return this._s_;
    }

    public void setS(PS node)
    {
        if(this._s_ != null)
        {
            this._s_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._s_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._l_)
            + toString(this._comma_)
            + toString(this._s_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._l_ == child)
        {
            this._l_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._s_ == child)
        {
            this._s_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._l_ == oldChild)
        {
            setL((PL) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._s_ == oldChild)
        {
            setS((PS) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
