/* This file was generated by SableCC (http://www.sablecc.org/). */

package fet.compiler.node;

import fet.compiler.analysis.*;

@SuppressWarnings("nls")
public final class TIdent extends Token
{
    public TIdent()
    {
        super.setText("x");
    }

    public TIdent(int line, int pos)
    {
        super.setText("x");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIdent(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIdent(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TIdent text.");
    }
}
