/* This file was generated by SableCC (http://www.sablecc.org/). */

package fet.compiler.node;

import fet.compiler.analysis.*;

@SuppressWarnings("nls")
public final class TLpar extends Token
{
    public TLpar()
    {
        super.setText("(");
    }

    public TLpar(int line, int pos)
    {
        super.setText("(");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TLpar(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLpar(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TLpar text.");
    }
}
