/* This file was generated by SableCC (http://www.sablecc.org/). */

package fet.calc.analysis;

import fet.calc.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseATermExpre(ATermExpre node);
    void caseAPlusExpre(APlusExpre node);
    void caseAMinusExpre(AMinusExpre node);
    void caseAFactorTerm(AFactorTerm node);
    void caseAMultTerm(AMultTerm node);
    void caseADivTerm(ADivTerm node);
    void caseANumberFactor(ANumberFactor node);
    void caseAIdFactor(AIdFactor node);
    void caseAExpreFactor(AExpreFactor node);

    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTLPar(TLPar node);
    void caseTRPar(TRPar node);
    void caseTBlank(TBlank node);
    void caseTNumber(TNumber node);
    void caseTId(TId node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
